# SITE SETTINGS
title: Petridish
description: Jekyll theme for research project websites
email: your.email@example.com
author: Peter Desmet
# url: "https://peterdesmet.github.io"
# baseurl: "/petridish"

# SOCIAL PROFILES
twitter_username: peterdesmet
github_username: peterdesmet

# THEME SETTINGS (ALL OPTIONAL)

logo: assets/img/petri-dish_1f9eb.png # Navbar logo, will be displayed with 30px height
posts_on_home: 3 # Number of posts to include on homepage, can be 0
custom_var: black;

# BUILD SETTINGS
markdown: kramdown
plugins: # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec

# FRONTMATTER DEFAULTS
defaults:
  # Use "default" template by default. This is implied for websites using a theme,
  # but Petridish demo site does not use a theme, so needs to be set explicitely.
  -
    scope:
      path: ""
    values:
      layout: "default"
  
  # Define permalinks for all posts
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:slug/"
