# SITE SETTINGS

title: Petridish
description: Jekyll theme for research project websites
email: your.email@example.com
author: Peter Desmet
# url: "https://peterdesmet.github.io"
# baseurl: "/petridish"

# SOCIAL PROFILES

twitter_username: peterdesmet
github_username: peterdesmet

# THEME SETTINGS

logo: assets/img/petri-dish_1f9eb.png # Optional site logo in navbar, will be displayed with 30px height
posts_on_home: 3 # Number of posts to include on homepage. Set to 0 or remove if you don't want any.
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/" # Permalink for categories, used in _includes/jumbotron.html & _includes/card.html
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # Use the "page" template by default for pages
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page" # Use the "page" template by default for posts as well
      permalink: "/blog/:slug/" # Permalink for your posts, can be changed

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-archives
  # - jekyll-feed
  # - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec
