# SITE SETTINGS

title: Petridish
description: Jekyll theme for research project websites
email: your.email@example.com
author: Peter Desmet
# url: "https://peterdesmet.github.io"
# baseurl: "/petridish"

# SOCIAL PROFILES

twitter_username: peterdesmet
github_username: peterdesmet

# TEMPLATE SETTINGS

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page" # TODO: update to post
      permalink: "/news/:slug/"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# BUILD SETTINGS

markdown: kramdown
plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec
