# SITE SETTINGS

title: Petridish
description: Jekyll theme for research project websites
email: your.email@example.com
author: Peter Desmet
# url: "https://peterdesmet.github.io"
# baseurl: "/petridish"

# SOCIAL PROFILES

twitter_username: peterdesmet
github_username: peterdesmet

# TEMPLATE SETTINGS

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:slug/"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# THEME SETTINGS

logo: assets/img/petri-dish_1f9eb.png
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/" # Also used in _includes/jumbotron.html & _includes/card.html

# BUILD SETTINGS

markdown: kramdown
plugins:
  - jekyll-archives
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec
